package com.mirea;

public enum ActionDoc {
    DOCUMENT_CREATED,
    DOCUMENT_EDITED,
    DOCUMENT_SEARCHED_BY_THE_NAME,
    DOCUMENT_SEARCHED_BY_THE_TYPE,
    DOCUMENT_SEARCHED_BY_DATA_OF_CREATION,
    DOCUMENT_SEARCHED_BY_DATA_OF_EDITION,
    DOCUMENT_SEARCHED_BY_AUTHOR_ID,
    DOCUMENT_SEARCHED_BY_DOCUMENT_ID,
    DOCUMENT_UPDATED
}
